config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: '', path_names: { sign_out: 'logout'}
  devise_scope :user do
    get '/logout', to: 'devise/sessions#destroy'
  end

  authenticated :user do
    root to: "pages#index"
  end

  unauthenticated :user do
    root to: "pages#home"
  end

  get '/call', to: 'pages#call'

  get '/establish_call/:contact_id', to: 'pages#establish_call', as: 'establish_call'

  post '/accept_call', to: 'pages#accept_call', as: 'accept_call/'

  patch '/accept_call/:request_id', to: 'requests#update', as: 'update_request'

  get '/contacts', to: 'pages#index'
  get '/setting', to: 'users#setting'
  patch '/setting', to: 'users#update_setting', as: 'update_setting'
  post '/sessions', to: 'video_sessions#create'

  post '/chat_rooms/chat_room_sessions', to: 'chat_rooms#create'

  resources :chat_rooms, only: [ :show, :destroy ] do
    # testing action cable
    post '/cable_testing', to: 'pages#cable_testing'
    post '/send_message', to: 'pages#send_message'
    post '/translate', to: 'pages#translate'
    post '/translate_message', to: 'pages#translate_message'
  end

  mount ActionCable.server, at: '/cable'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/home', to: 'pages#home'

  get '/users/:id', to: 'users#show', as: :user
  get '/users/:id/edit', to: 'users#edit', as: :user_edit
  patch '/users/:id', to: 'users#update'
  delete '/users/:id', to: 'users#destroy'

  resources :connections, only: [:create, :destroy]
  get '/add_contact', to: 'connections#new', as: :add_contact
end

app/models/connection.rb
class Connection < ApplicationRecord
  belongs_to :user
  belongs_to :contact, class_name: 'User', foreign_key: 'contact_id'

  after_create :create_inverted_connection

  private

  def create_inverted_connection
    unless Connection.where('user_id = ? and contact_id = ?', self.contact.id, self.user.id).length > 0
      inverted = Connection.create!(user: self.contact, contact: self.user)
    end
  end
end

app/controllers/connections_controller.rb
class ConnectionsController < ApplicationController
  def new
  end

  def create
    @connection = Connection.new
    @connection.user = current_user
    contact_user = User.find_by(email: params[:user][:email])
    @connection.contact = contact_user

    if @connection.save
      contact_message = nil
      if contact_user.first_name.nil? || contact_user.last_name.nil?
        contact_message = "#{contact_user.email}"
      else
        contact_message = "#{contact_user.first_name} #{contact_user.last_name}"
      end
      flash[:notice] = "Added #{contact_message} to contacts"
      redirect_to contacts_path
    else
      flash[:alert] = "Invalid email address!"
      render 'new'
    end
  end

  def destroy
    connection = current_user.connections.find_by(contact_id: params[:id].to_i)
    connection.destroy
    redirect_to root_path
  end
end

app/views/connections/new.html.erb
<% params["action"] = "Add contact" %>

<div class="center-screen">
  <div class="align-center">
    <div class="container">
      <div class="row">
        <div class="col-xs-offset-2 col-xs-8 col-xs-offset-2">
          <h2>Enter an email address:</h2>
        </div>
        <%= simple_form_for User.new, url: connections_path, class: "input-group" do |f| %>
          <div class="col-xs-offset-2 col-xs-8 col-xs-offset-2 ">
            <div class="flex-inline">
              <%= f.input_field :email, class: "form-control margin-right" %>
              <div class="input-group-append">
              <%= f.button :submit, value: "Add Contact" , class: "btn btn-primary" %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>