config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: '', path_names: { sign_out: 'logout'}
  devise_scope :user do
    get '/logout', to: 'devise/sessions#destroy'
  end

  authenticated :user do
    root to: "pages#index"
  end

  unauthenticated :user do
    root to: "pages#home"
  end

  get '/call', to: 'pages#call'

  get '/establish_call/:contact_id', to: 'pages#establish_call', as: 'establish_call'

  post '/accept_call', to: 'pages#accept_call', as: 'accept_call/'

  patch '/accept_call/:request_id', to: 'requests#update', as: 'update_request'

  get '/contacts', to: 'pages#index'
  get '/setting', to: 'users#setting'
  patch '/setting', to: 'users#update_setting', as: 'update_setting'
  post '/sessions', to: 'video_sessions#create'

  post '/chat_rooms/chat_room_sessions', to: 'chat_rooms#create'

  resources :chat_rooms, only: [ :show, :destroy ] do
    # testing action cable
    post '/cable_testing', to: 'pages#cable_testing'
    post '/send_message', to: 'pages#send_message'
    post '/translate', to: 'pages#translate'
    post '/translate_message', to: 'pages#translate_message'
  end

  mount ActionCable.server, at: '/cable'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/home', to: 'pages#home'

  get '/users/:id', to: 'users#show', as: :user
  get '/users/:id/edit', to: 'users#edit', as: :user_edit
  patch '/users/:id', to: 'users#update'
  delete '/users/:id', to: 'users#destroy'

  resources :connections, only: [:create, :destroy]
  get '/add_contact', to: 'connections#new', as: :add_contact
end

app/models/user.rb
class User < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :connections
  has_many :chat_room_participations
  has_many :chat_rooms, through: :chat_room_participations
  has_many :requests

  validates :email, uniqueness: true

  mount_uploader :photo, PhotoUploader

  def contacts
    self.connections.map do |connection|
      connection.contact
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:edit, :update, :show, :destroy]

  def edit; end

  def update
    @user.update(user_params)
    redirect_to user_edit_path(@user)
  end

  def create
      # Untested Code
    user = User.new(user_params)
    authorize user # I don't know where to put this TODO: Test this method
    if user.save
      redirect_to user_path(user)
    else
      raise
    end
  end

  def show; end

  def destroy
    @user.destroy
    redirect_to root_path
  end

  def setting
    @user = current_user
    require "google/cloud/translate"

    keyfile = ENV['TRANSLATION_CREDENTIALS']
    creds = Google::Cloud::Translate::Credentials.new(keyfile)

    translate = Google::Cloud::Translate.new(
      project_id: ENV["PROJECT_ID"],
      credentials: creds
    )

    @languages = translate.languages("en")
  end

  def update_setting
    current_user.update(user_params)
    puts ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
    puts current_user.language
    current_user.save
    redirect_to setting_path
  end

  private

  def find_user
    @user = User.find(params[:id])
    #authorize @user
  end


  def user_params
    params.require(:user).permit(:email, :first_name, :last_name, :description, :photo, :language, :caption_font, :caption_font_size, :enable_transcript)
  end
end

app/views/users/edit.html.erb
<div class="profile-container">
  <%= simple_form_for(@user) do |t| %>
    <div class="profile-form">
      <div>
        <%= t.input :email  %>
        <%= t.input :first_name %>
        <%= t.input :last_name %>
        <%= t.input :password %>
        <%= t.input :photo %>
        <div class="small-profile-pic hidden-md hidden-lg">
          <% if @user.photo.url.nil? %>
            <%= image_tag "https://upload.wikimedia.org/wikipedia/commons/8/89/Portrait_Placeholder.png"%>
          <% else %>
            <%= cl_image_tag current_user.photo%>
          <% end %>
        </div>
        <%= t.submit :Save, class: "btn btn-primary save-btn form-control" %>
        <p></p>
        <%= link_to "View my profile", user_path(@user), class: "btn btn-primary save-btn form-control" %>
      </div>
      <div class="profile-pic hidden-xs hidden-sm">
        <% if @user.photo.url.nil? %>
          <%= image_tag "https://upload.wikimedia.org/wikipedia/commons/8/89/Portrait_Placeholder.png"%>
        <% else %>
          <%= cl_image_tag current_user.photo%>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/setting.html.erb
<div id="settings-page"></div>

<% language_names = [] %>

<% @languages.each do |language| %>
  <% language_names << language.name %>
<% end %>

<% fonts = [
    "Arial",
    "Times New Roman",
    "Calibri"
  ] %>

<div class="container">
  <div class="contacts-container">
    <div class="row">
      <div class="col-xs-12 col-md-6">
        <div class="settings">
          <h2>Settings</h2>
          <div>
            <%= simple_form_for(current_user, url: update_setting_path) do |t| %>
              <div>
                <div class="card card-form card-form-no-hover">
                  <%= t.label :language, class:'padding-right no-margin font-weight-normal' %>
                  <%= t.input_field :language, collection: language_names, class:'input-field-text-black input-dropdown form-control', include_blank: false %>
                </div>
                <div class="card card-form card-form-no-hover">
                  <%= t.label :caption_font, class:'padding-right no-margin font-weight-normal' %>
                  <%= t.input_field :caption_font, collection: fonts.sort, class:'input-field-text-black input-dropdown form-control' %>
                </div>
                <div class="card card-form card-form-no-hover">
                  <%= t.label :caption_font_size, class:'padding-right no-margin font-weight-normal' %>
                  <%= t.input_field :caption_font_size, class:'input-field-text-black input-dropdown form-control' %>
                </div>
                <div class="card card-form card-form-no-hover">
                  <%= t.label :enable_transcript, class:'padding-right no-margin font-weight-normal' %>
                  <label class="switch">
                    <%= t.input_field :enable_transcript, class:'input-field-text-black' %>
                    <span class="slider round"></span>
                  </label>
                </div>
                <%= t.button :submit, value: 'Save', class: "btn btn-primary save-btn form-control" %>
                <p></p>
              </div>
            <% end %>
                <%#= link_to "Save", update_setting_path, method: :patch, class: "btn btn-primary save-btn form-control" %>
          </div>
        </div>
      </div>
      <div class="col-xs-12 col-md-6 hidden-xs hidden-sm">
        <div class="video-feed">
          <div class="video-content">
            <video id="settings-video" class="flex-video" autoplay=""></video>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>


<%= javascript_pack_tag 'settings_video' %>

app/views/users/show.html.erb
<div class="user-container">
  <div class="row">
    <div class="col-xs-12 col-md-3 vcenter">
      <div class="profile-pic vertical-padding">
        <% if @user.photo.url.nil? %>
          <%= image_tag "https://upload.wikimedia.org/wikipedia/commons/8/89/Portrait_Placeholder.png", class: "img-circle img-profile"%>
        <% else %>
          <%= cl_image_tag @user.photo, class: "img-circle img-profile"%>
        <% end %>
      </div>
    </div>
    <div class="col-xs-12 col-md-4 vcenter">
      <div class="profile-text vertical-padding">
        <h1><%= @user.first_name %> <%= @user.last_name %></h1>
        <h2 class="italics" ><%= @user.email %></h2>
      </div>
    </div>
    <div class="col-xs-12 col-md-4 vcenter">
      <div class="flex-end vertical-padding">
        <%= link_to "Edit Information", user_edit_path(@user), class: "btn btn-primary vertical-margin" %>
        <%= link_to "Delete Account", user_path(@user), class: "btn btn-danger vertical-margin", method: :delete, data: {
            confirm: "Are you sure?"
          } %>
      </div>
    </div>
  </div>
</div>