config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: '', path_names: { sign_out: 'logout'}
  devise_scope :user do
    get '/logout', to: 'devise/sessions#destroy'
  end

  authenticated :user do
    root to: "pages#index"
  end

  unauthenticated :user do
    root to: "pages#home"
  end

  get '/call', to: 'pages#call'

  get '/establish_call/:contact_id', to: 'pages#establish_call', as: 'establish_call'

  post '/accept_call', to: 'pages#accept_call', as: 'accept_call/'

  patch '/accept_call/:request_id', to: 'requests#update', as: 'update_request'

  get '/contacts', to: 'pages#index'
  get '/setting', to: 'users#setting'
  patch '/setting', to: 'users#update_setting', as: 'update_setting'
  post '/sessions', to: 'video_sessions#create'

  post '/chat_rooms/chat_room_sessions', to: 'chat_rooms#create'

  resources :chat_rooms, only: [ :show, :destroy ] do
    # testing action cable
    post '/cable_testing', to: 'pages#cable_testing'
    post '/send_message', to: 'pages#send_message'
    post '/translate', to: 'pages#translate'
    post '/translate_message', to: 'pages#translate_message'
  end

  mount ActionCable.server, at: '/cable'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/home', to: 'pages#home'

  get '/users/:id', to: 'users#show', as: :user
  get '/users/:id/edit', to: 'users#edit', as: :user_edit
  patch '/users/:id', to: 'users#update'
  delete '/users/:id', to: 'users#destroy'

  resources :connections, only: [:create, :destroy]
  get '/add_contact', to: 'connections#new', as: :add_contact
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="polyglot-navbar">
  <div class="logo"><%= link_to "Polyglot", contacts_path %></div>

  <div class="right-align hidden-xs hidden-sm">
    <div class="links">
      <div id="contacts"><%= link_to "Contacts", contacts_path %></div>
      <div id="settings"><%= link_to "Settings", setting_path %></div>
    </div>
    <div class="profile">
      <% if current_user.nil? %>
        <%= link_to "Login", new_user_session_path  %>
      <% else %>
        <div class="dropdown">
          <div data-toggle="dropdown">
            <% if current_user.photo.url.nil? %>
              <img src="https://upload.wikimedia.org/wikipedia/commons/8/89/Portrait_Placeholder.png" class="avatar dropdown-toggle img-circle">
            <% else %>
              <%= cl_image_tag(current_user.photo, class: "avatar dropdown-toggle img-circle", transformation: [
          { gravity: "face:auto", width: 500, height: 500, radius: "max", crop: "crop" }
        ])%>
            <% end %>
          </div>
          <ul class="dropdown-menu dropdown-menu-right polyglot-dropdown">
            <li><%= link_to "Profile", user_path(current_user) %></li>
            <li><%= link_to "Logout", destroy_user_session_path %></li>
          </ul>
        </div>
      <% end %>
    </div>
  </div>

  <div class="burger-menu hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right polyglot-dropdown">
        <li><%= link_to "Contacts", contacts_path %></li>
        <li><%= link_to "Settings", setting_path %></li>
          <% if current_user.nil? %>
            <li><%= link_to "Login", new_user_session_path  %></li>
          <% else %>
            <li><%= link_to "Profile", user_path(current_user) %></li>
            <li><%= link_to "Logout", destroy_user_session_path %></li>
          <% end %>
      </ul>
    </div>
  </div>
</div>