config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: '', path_names: { sign_out: 'logout'}
  devise_scope :user do
    get '/logout', to: 'devise/sessions#destroy'
  end

  authenticated :user do
    root to: "pages#index"
  end

  unauthenticated :user do
    root to: "pages#home"
  end

  get '/call', to: 'pages#call'

  get '/establish_call/:contact_id', to: 'pages#establish_call', as: 'establish_call'

  post '/accept_call', to: 'pages#accept_call', as: 'accept_call/'

  patch '/accept_call/:request_id', to: 'requests#update', as: 'update_request'

  get '/contacts', to: 'pages#index'
  get '/setting', to: 'users#setting'
  patch '/setting', to: 'users#update_setting', as: 'update_setting'
  post '/sessions', to: 'video_sessions#create'

  post '/chat_rooms/chat_room_sessions', to: 'chat_rooms#create'

  resources :chat_rooms, only: [ :show, :destroy ] do
    # testing action cable
    post '/cable_testing', to: 'pages#cable_testing'
    post '/send_message', to: 'pages#send_message'
    post '/translate', to: 'pages#translate'
    post '/translate_message', to: 'pages#translate_message'
  end

  mount ActionCable.server, at: '/cable'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/home', to: 'pages#home'

  get '/users/:id', to: 'users#show', as: :user
  get '/users/:id/edit', to: 'users#edit', as: :user_edit
  patch '/users/:id', to: 'users#update'
  delete '/users/:id', to: 'users#destroy'

  resources :connections, only: [:create, :destroy]
  get '/add_contact', to: 'connections#new', as: :add_contact
end

app/views/pages/_contact.html.erb
<div class="card">
  <div class="info">
    <% if contact.photo.url.nil? %>
      <img src="https://upload.wikimedia.org/wikipedia/commons/8/89/Portrait_Placeholder.png" class="avatar profile dropdown-toggle img-circle" width=65>
    <% else %>
      <%= cl_image_tag(contact.photo, class: "profile avatar dropdown-toggle img-circle", width:65, transformation: [
          { gravity: "face:auto", width: 500, height: 500, radius: "max", crop: "crop" }
        ])%>
    <% end %>
    <div class="text text-color">
      <% if contact.first_name.nil? || contact.last_name.nil? %>
        <p><%= contact.email %></p>
      <% else %>
        <p><%= contact.first_name %> <%= contact.last_name %></p>
      <% end %>
      <p class="darker">Last call: <%= Time.now %></p>
    </div>
  </div>
  <div class="call" data-user-id="<%= contact.id %>">
    <!-- Calls establish_call in pages_controller -->
    <%= link_to establish_call_path(contact.id), remote: true, class: "modalTrigger", data: {'user-id': contact.id } do  %>
      <i class="fas fa-phone"></i>
    <% end %>
  </div>
   <%= link_to connection_path(contact), method: :delete do %>
   <button type="button" class="close close-location" data-dismiss="modal" aria-label="close"><span aria-hidden="true">×</span></button>
   <% end %>
</div>

<!-- Modal -->
<div class="modal fade" id="myModal<%= contact.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="vertical-alignment-helper">
    <div class="modal-dialog vertical-align-center">
      <div class="modal-content modal-color">
        <div class="modal-header">
          <%= link_to "#", class:"pull-right", 'data-dismiss':"modal", 'data-target':"#myModal#{contact.id}" do  %>
            <i class="fas fa-times-circle"></i>
          <% end %>

            <div class="modal-container">
              <% if contact.photo.url.nil? %>
                <img src="https://upload.wikimedia.org/wikipedia/commons/8/89/Portrait_Placeholder.png" class="avatar profile dropdown-toggle img-circle modal-picture" width=150>
              <% else %>
                <%= cl_image_tag(contact.photo, class: "profile avatar dropdown-toggle img-circle modal-picture", width:150, transformation: [
          { gravity: "face:auto", width: 500, height: 500, radius: "max", crop: "crop" }])%>
              <% end %>
              <div class="modal-text">
                <h4 class="modal-title" id="myModalLabel">Calling</h4>
                <h4>
                  <strong>
                    <% if contact.first_name.nil? || contact.last_name.nil? %>
                      <p><%= contact.email %></p>
                    <% else %>
                      <p><%= contact.first_name %> <%= contact.last_name %></p>
                    <% end %>
                  </strong>
                </h4>
              </div>
            </div>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/call.html.erb
<!--
<div class="call-container">
  <div id="remote-video-container">
    <div id="video_overlays">
      <video id="local-video" autoplay></video>
    </div>
  </div>
</div>
 -->



<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

<hr />
<div>
  <span class="text-color" style="display:none">Random User ID:</span>
  <span id="current-user" class="text-color" style="display:none"><%= rand(0..10000) %></span>
</div>

<button onclick="handleJoinSession()">
  Join Room
</button>

<button onclick="handleLeaveSession()">
  Leave Room
</button>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(5,25,55,0.3) 0%, rgba(68,73,101,0.3),rgba(128,129,149,0.3),rgba(191,190,200,0.3),rgba(255,255,255,0.3) 50%), url('<%= image_path 'phone.jpg' %>');">
  <div class="banner-content">
    <h1>Make a call</h1>
    <p>Communicate in different languages</p>
    <p>and receive real-time translated</p>
    <p> chat in your native tongue.</p>
    <p>
      <span id="banner-typed-text"></span>
    </p>
    <%= link_to "Sign Up",new_user_registration_path, class: "btn btn-primary btn-lg" %>
    <%= link_to "Login", new_user_session_path, class: "btn btn-primary btn-lg" %>
  </div>
</div>

<% unless current_user.nil? %>

<% end %>

app/views/pages/index.html.erb
<div id="contacts-page"></div>

<!-- CONTACTS PAGE -->
<div class="container">
  <div class="contacts-container text-color">
    <div class="row">
      <div class="col-xs-12 col-md-6">
        <div class="contacts">
          <div class="contacts-header">
            <h2>Contacts</h2>
            <%= link_to add_contact_path do %>
              <i class="fas fa-plus-square"></i>
            <% end %>
          </div>
          <div class="contacts-list">
            <% current_user.contacts.each do |contact| %>
              <%= render "pages/contact", contact: contact %>
            <% end %>
          </div>
        </div>
      </div>

      <div class="col-xs-12 col-md-6 hidden-xs hidden-sm">
        <div class="video-feed">
          <div class="video-content">
            <video id="contacts-video" class="flex-video" autoplay=""></video>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- INFORMATION TO BE PASSED TO NOTIFICATIONS.JS -->
<div id="my-user-id" data-user-id="<%= current_user.id %>"></div>
<input type="hidden" id="caller-id" name="caller_id" value=""/>

<!-- Modal -->
<div class="modal fade" id="calleeModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="vertical-alignment-helper">
    <div class="modal-dialog vertical-align-center">
      <div class="modal-content modal-color">
        <div class="modal-header">

            <div class="modal-container">
              <img src="https://upload.wikimedia.org/wikipedia/commons/8/89/Portrait_Placeholder.png" class="avatar profile dropdown-toggle img-circle modal-picture" width=150 id="caller-photo">
              <div class="modal-text">
                <h4>
                  <strong id=caller-name class="text-color">
                    SOMEONE
                  </strong>
                </h4>
                <h4 class="modal-title text-color" id="myModalLabel">is calling</h4>

                <div class="flex-inline">
                  <form action="/accept_call" method="post">
                    <input type="hidden" id="chat-room-id" name="chat_room_id" value=""/>
                    <button type="submit" id="accept-button" class="accept-call-button">
                      <i class="fas fa-check-circle"></i>
                    </button>
                  </form>
                  <%= link_to "#", class:"pull-right", 'data-dismiss':"modal", 'data-target':"#calleeModal" do  %>
                    <i class="fas fa-times-circle"></i>
                  <% end %>
                </div>
              </div>
            </div>

        </div>
      </div>
    </div>
  </div>
</div>

<%= javascript_pack_tag 'local_video' %>
<%# javascript_pack_tag 'notifications' %>

app/views/pages/new.html.erb
<%= simple_form_for(@page) do |p| %>

  <%= p.input :first_name, as: :text, input_html: { autocomplete: "off" } %>
  <%= p.input :last_name, as: :text, input_html: { autocomplete: "off" } %>
  <%= p.input :email, as: :text, input_html: { autocomplete: "off" } %>
  <%= p.input :photo %>
  <%= p.input :photo_cache, as: :hidden %>

  <%= p.button :submit, class: "btn btn-primary" %>
<% end %>